---
name: Release Drafter
tag: v{{version}}
categories:
  - title: ✨ Features
    labels:
      - feature
  - title: 🐞 Bug Fixes
    labels:
      - bug
  - title: 📄 Documentation
    labels:
      - documentation
  - title: 🔧 Maintenance
    labels:
      - maintenance
template: |
  ## 🚀 Release Notes for v{{version}}

  ### ✨ Features
  {{#changelog.feature}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.feature}}

  ### 🐞 Bug Fixes
  {{#changelog.bug}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.bug}}

  ### 📄 Documentation
  {{#changelog.documentation}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.documentation}}

  ### 🔧 Maintenance
  {{#changelog.maintenance}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.maintenance}}

  ## 🏅 Contributors
  {{#contributors}}
  - @{{username}}
  {{/contributors}}
