name: Release Drafter
<<<<<<< HEAD
tag: "$NEW_VERSION"
categories:
  - title: "✨ Features"
    labels:
      - "feature"
  - title: "🐞 Bug Fixes"
    labels:
      - "bug"
  - title: "📄 Documentation"
    labels:
      - "documentation"
  - title: "🔧 Maintenance"
    labels:
      - "maintenance"
template: |
  ## 🚀 Release Notes for $NEW_VERSION
=======
tag: "v{{Resolvedversion}}"
categories:

  - label: feature
    title: ✨ Features
  - label: bug
    title: 🐞 Bug Fixes
  - label: documentation
    title: 📄 Other Changes
  - label: maintenance
    title: 🔧 Maintenance
template: |
 
  ## 🚀 Release Notes for v{{version}}
>>>>>>> b1710f8dae9f1d7254d78887c9d69929ce764e42


  ### ✨ Features
  {{#changelog.feature}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.feature}}
  {{^changelog.feature}}
  No feature changes in this release.
  {{/changelog.feature}}

  ### 🐞 Bug Fixes
  {{#changelog.bug}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.bug}}
  {{^changelog.bug}}
  No bug fixes in this release.
  {{/changelog.bug}}

  ### 📄 Documentation
  {{#changelog.documentation}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.documentation}}
  {{^changelog.documentation}}
  No documentation updates in this release.
  {{/changelog.documentation}}

  ### 🔧 Maintenance
  {{#changelog.maintenance}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.maintenance}}
  {{^changelog.maintenance}}
  No maintenance updates in this release.
  {{/changelog.maintenance}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME

  {{/contributors}}
  {{^contributors}}
  No contributors in this release.
  {{/contributors}}
