name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "✨ Features"
    labels:
      - feature
      - enhancement
      - new-feature
      - feat
  - title: "🐞 Bug Fixes"
    labels:
      - fix
      - bugfix
      - bug
      - defect
  - title: "📄 Other Changes"
    labels:
      - other
      - documentation
      - docs
  - title: "🔧 Maintenance"
    labels:
      - chore
      - refactor
      - maintenance

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR: $BODY'

version-resolver:
  major:
    labels:
      - major
      - breaking-change
  minor:
    labels:
      - minor
      - feature
      - feat
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bug
      - chore
      - maintenance
  default: patch

template: |
  🚀 Release Notes for $RESOLVED_VERSION

  template: |
  ## 🚀 Release Notes for $NEW_VERSION

  ### ✨ Features
  {{#pullRequests}}
  {{#contains $BODY '### Features'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ### 🐞 Bug Fixes
  {{#pullRequests}}
  {{#contains $BODY '### Bug Fixes'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ### 📄 Documentation
  {{#pullRequests}}
  {{#contains $BODY '### Documentation'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME
  {{/contributors}}