name: Release Drafter
tag: "v{{Resolvedversion}}"
categories:

  - label: feature
    title: ✨ Features
  - label: bug
    title: 🐞 Bug Fixes
  - label: documentation
    title: 📄 Other Changes
  - label: maintenance
    title: 🔧 Maintenance
template: |
 
  ## 🚀 Release Notes for v{{version}}


  ### ✨ Features
  {{#changelog.feature}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.feature}}

  ### 🐞 Bug Fixes
  {{#changelog.bug}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.bug}}

  ### 📄 Documentation
  {{#changelog.documentation}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.documentation}}

  ### 🔧 Maintenance
  {{#changelog.maintenance}}
  - {{title}} (#{{number}}) by @{{author}}: {{body}}
  {{/changelog.maintenance}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME

  {{/contributors}}
