<<<<<<< HEAD
name: Release Drafter
categories:
  - label: feature
    title: ✨ Features
  - label: bug
    title: 🐞 Bug Fixes
  - label: documentation
    title: 📄 Other Changes
  - label: maintenance
    title: 🔧 Maintenance
template: |
=======
---
name: Release Drafter
categories:
  Features:
    - label: feature
    - title: ✨ Features
  Bug Fixes:
    - label: bug
    - title: 🐞 Bug Fixes
  Other Changes:
    - label: documentation
    - title: 📄 Other Changes
  Maintenance:
    - label: maintenance
    - title: 🔧 Maintenance
template: |
  ## 🚀 Release Notes for $NEW_VERSION

  template: |
>>>>>>> 3ced03065d638b37044d8f9d7695f81766ccbc85
  ## 🚀 Release Notes for $NEW_VERSION

  ### ✨ Features
  {{#pullRequests}}
  {{#contains $BODY '### Features'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ### 🐞 Bug Fixes
  {{#pullRequests}}
  {{#contains $BODY '### Bug Fixes'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ### 📄 Documentation
  {{#pullRequests}}
  {{#contains $BODY '### Documentation'}}
  - $TITLE (#$NUMBER) by @$AUTHOR: $BODY
  {{/contains}}
  {{/pullRequests}}

  ## 🏅 Contributors
  {{#contributors}}
  - @$USERNAME
  {{/contributors}}
